-- Generated by Oracle SQL Developer REST Data Services 18.3.0.277.2354
-- Exported REST Definitions from ORDS Schema Version 18.4.0.r3541002
-- Schema: ORDER_PROCESSING   Date: Wed Mar 13 12:41:10 PDT 2019
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ORDER_PROCESSING',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'order_processing',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'customer',
      p_base_path      => '/customers/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'customer',
      p_pattern        => 'customer',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'customer',
      p_pattern        => 'customer',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    L_CU CLOB := :body_text;
BEGIN
insert into debug_t values (l_cu);
--INSERT INTO customer_t (id, first_name, last_name, title) values (29, ''a'', ''b'', ''c'');

INSERT INTO customer_t (id, first_name, last_name, title, notification_on, email, slack_handle, twitter_handle)
      SELECT * FROM json_table(L_CU, ''$''
         COLUMNS (
           id                  	NUMBER     PATH ''$.id'',
           first_name           VARCHAR2   PATH ''$.firstName'',
           last_name          	VARCHAR2   PATH ''$.lastName'',
           title          		VARCHAR2   PATH ''$.title'',
           notification_on      VARCHAR2   PATH ''$.notificationOn'',
           email      			VARCHAR2   PATH ''$.email'',
           slack_handle 		VARCHAR2   PATH ''$.slackHandle'',
           twitter_handle 		VARCHAR2   PATH ''$.twitterHandle''
));

INSERT INTO address_t (customer_id, id, street, nr, city, postcode, country)
SELECT * FROM json_table(L_CU , ''$''
         COLUMNS (
           customer_id  Number PATH ''$.id'',
           NESTED                      PATH ''$.addresses[*]''
             COLUMNS (
               id       		NUMBER      PATH ''$.id'',
               street  			VARCHAR2    PATH ''$.street'',
               nr  				VARCHAR2    PATH ''$.number'',
               city  			VARCHAR2    PATH ''$.city'',
               postcode  		VARCHAR2    PATH ''$.postcode'',
               country  		VARCHAR2    PATH ''$.country''
)));


COMMIT;

END;'
      );


  COMMIT; 
END;
/